[font]
normal = {family = "FiraCode Nerd Font", style="Medium"}
size = 12.0

[window]
decorations = "None"
opacity =  0.87
padding = {x = 5, y = 5}


# [colors.primary]
# background = "0xfffdf6"
# foreground = "0x323232"
#
# [colors.cursor]
# text = "0x323232"
# cursor = "0x808080"
#
# [colors.normal]
# black = "0x000000"
# red = "0xcc241d"
# green = "0x98971a"
# yellow = "0xd79921"
# blue = "0x458588"
# magenta = "0xb16286"
# cyan = "0x689d6a"
# white = "0xa89984"
#
# [colors.bright]
# black = "0x928374"
# red = "0xfb4934"
# green = "0xb8bb26"
# yellow = "0xfabd2f"
# blue = "0x83a598"
# magenta = "0xd3869b"
# cyan = "0x8ec07c"
# white = "0xebdbb2"
